const wordLists=[
  { keyword: "banana", hint: "Yellow fruit often associated with monkeys." },
  { keyword: "elephant", hint: "Large mammal with a long trunk." },
  {
    keyword: "pizza",
    hint: "Popular Italian dish with cheese and tomato sauce on a round dough base.",
  },
  { keyword: "computer", hint: "Electronic device used for processing data." },
  {
    keyword: "sunflower",
    hint: "Tall plant with large yellow flowers that turn towards the sun.",
  },
  {
    keyword: "mountain",
    hint: "Large landform that rises prominently above its surroundings.",
  },
  {
    keyword: "guitar",
    hint: "Musical instrument with strings that is typically played by plucking or strumming.",
  },
  {
    keyword: "ocean",
    hint: "Vast body of saltwater that covers most of the Earth's surface.",
  },
  {
    keyword: "book",
    hint: "Collection of written or printed pages bound together.",
  },
  {
    keyword: "cat",
    hint: "Domesticated carnivorous mammal with soft fur, retractile claws, and typically a short snout.",
  },
  {
    keyword: "coffee",
    hint: "Beverage made from roasted and ground coffee beans.",
  },
  { keyword: "football", hint: "Popular team sport played with an oval ball." },
  { keyword: "moon", hint: "Natural satellite of the Earth." },
  { keyword: "bicycle", hint: "Human-powered vehicle with two wheels." },
  {
    keyword: "chocolate",
    hint: "Sweet, brown food made from roasted and ground cacao seeds.",
  },
  {
    keyword: "tree",
    hint: "Tall perennial woody plant with a single main trunk.",
  },
  { keyword: "bird", hint: "Warm-blooded vertebrate with feathers and wings." },
  {
    keyword: "rainbow",
    hint: "Optical and meteorological phenomenon that causes a spectrum of light to appear in the sky.",
  },
  {
    keyword: "flower",
    hint: "Reproductive structure found in flowering plants.",
  },
  {
    keyword: "dragon",
    hint: "Mythical creature typically represented as a large, serpentine, fire-breathing reptile.",
  },
  {
    keyword: "car",
    hint: "Four-wheeled motor vehicle used for transportation.",
  },
  { keyword: "phone", hint: "Electronic device used for communication." },
  {
    keyword: "candle",
    hint: "Wax stick with a wick that is lit to provide light.",
  },
  { keyword: "butterfly", hint: "Insect with large, often colorful wings." },
  { keyword: "star", hint: "Luminous celestial body." },
  { keyword: "ice cream", hint: "Frozen dessert made from cream and sugar." },
  { keyword: "beach", hint: "Sandy shore of a body of water." },
  {
    keyword: "rocket",
    hint: "Projectile that can be propelled to a great height or distance by the combustion of its contents.",
  },
  { keyword: "camera", hint: "Device used to capture images." },
  { keyword: "ship", hint: "Large watercraft for traveling on water." },
  { keyword: "diamond", hint: "Precious stone made of pure carbon." },
  {
    keyword: "unicorn",
    hint: "Mythical creature depicted as a horse with a single straight horn.",
  },
  { keyword: "rain", hint: "Precipitation in the form of liquid water drops." },
  {
    keyword: "rocket",
    hint: "Projectile that can be propelled to a great height or distance by the combustion of its contents.",
  },
  { keyword: "camera", hint: "Device used to capture images." },
  { keyword: "ship", hint: "Large watercraft for traveling on water." },
  { keyword: "diamond", hint: "Precious stone made of pure carbon." },
  {
    keyword: "unicorn",
    hint: "Mythical creature depicted as a horse with a single straight horn.",
  },
  { keyword: "rain", hint: "Precipitation in the form of liquid water drops." },
  { keyword: "butterfly", hint: "Insect with large, often colorful wings." },
  { keyword: "star", hint: "Luminous celestial body." },
  { keyword: "ice cream", hint: "Frozen dessert made from cream and sugar." },
  { keyword: "beach", hint: "Sandy shore of a body of water." },
  {
    keyword: "rocket",
    hint: "Projectile that can be propelled to a great height or distance by the combustion of its contents.",
  },
  { keyword: "camera", hint: "Device used to capture images." },
  { keyword: "ship", hint: "Large watercraft for traveling on water." },
  { keyword: "diamond", hint: "Precious stone made of pure carbon." },
  {
    keyword: "unicorn",
    hint: "Mythical creature depicted as a horse with a single straight horn.",
  },
  { keyword: "rain", hint: "Precipitation in the form of liquid water drops." },
  {
    keyword: "rocket",
    hint: "Projectile that can be propelled to a great height or distance by the combustion of its contents.",
  },
  { keyword: "camera", hint: "Device used to capture images." },
  { keyword: "ship", hint: "Large watercraft for traveling on water." },
  { keyword: "diamond", hint: "Precious stone made of pure carbon." },
  {
    keyword: "unicorn",
    hint: "Mythical creature depicted as a horse with a single straight horn.",
  },
  { keyword: "rain", hint: "Precipitation in the form of liquid water drops." },
  { keyword: "butterfly", hint: "Insect with large, often colorful wings." },
  { keyword: "star", hint: "Luminous celestial body." },
  { keyword: "ice cream", hint: "Frozen dessert made from cream and sugar." },
  { keyword: "beach", hint: "Sandy shore of a body of water." },
  {
    keyword: "rocket",
    hint: "Projectile that can be propelled to a great height or distance by the combustion of its contents.",
  },
  { keyword: "camera", hint: "Device used to capture images." },
  { keyword: "ship", hint: "Large watercraft for traveling on water." },
  { keyword: "diamond", hint: "Precious stone made of pure carbon." },
  {
    keyword: "unicorn",
    hint: "Mythical creature depicted as a horse with a single straight horn.",
  },
  { keyword: "rain", hint: "Precipitation in the form of liquid water drops." },
  {
    keyword: "rocket",
    hint: "Projectile that can be propelled to a great height or distance by the combustion of its contents.",
  },
  { keyword: "camera", hint: "Device used to capture images." },
  { keyword: "ship", hint: "Large watercraft for traveling on water." },
  { keyword: "diamond", hint: "Precious stone made of pure carbon." },
];
